Controllers/adminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TravelTrip_MVCProject.Models.Classes;

namespace TravelTrip_MVCProject.Controllers
{
    public class adminController : Controller
    {
        Context c = new Context();

        /*** BLOGLAR KOMUTLARI ***/
        public ActionResult BlogList()
        {
            var values = c.BlogTBLs.ToList();
            return View(values);
        }

        [HttpGet]
        public ActionResult AddNewBlog()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddNewBlog(BlogTBL blog)
        {
            c.BlogTBLs.Add(blog);
            c.SaveChanges();
            return RedirectToAction("BlogList");
        }

        public ActionResult DeleteBlog(int id)
        {
            var values = c.BlogTBLs.Find(id);
            c.BlogTBLs.Remove(values);
            c.SaveChanges();
            return RedirectToAction("BlogList");
        }

        [HttpGet]
        public ActionResult UpdateBlog(int id)
        {
            var blog = c.BlogTBLs.Find(id);
            return View("UpdateBlog", blog);
        }

        [HttpPost]
        public ActionResult UpdateBlog(BlogTBL b)
        {
            var blg = c.BlogTBLs.Find(b.ID);
            blg.Baslik = b.Baslik;
            blg.Tarih = b.Tarih;
            blg.Aciklama = b.Aciklama;
            blg.BlogFoto = b.BlogFoto;
            c.SaveChanges();
            return RedirectToAction("BlogList");
        }

        /*** YORUMLAR KOMUTLARI ***/
        public ActionResult CommentList()
        {
            var yorumlar = c.YorumlarTBLs.ToList();
            return View(yorumlar);
        }

        public ActionResult DeleteComment(int id)
        {
            var yorumlar = c.YorumlarTBLs.Find(id);
            c.YorumlarTBLs.Remove(yorumlar);
            c.SaveChanges();
            return RedirectToAction("CommentList");
        }

        [HttpGet]
        public ActionResult UpdateComment(int id)
        {
            var yorum = c.YorumlarTBLs.Find(id);
            return View("UpdateComment", yorum);
        }

        [HttpPost]
        public ActionResult UpdateComment(YorumlarTBL y)
        {
            var yrm = c.YorumlarTBLs.Find(y.ID);
            yrm.KullaniciAdi = y.KullaniciAdi;
            yrm.Email = y.Email;
            yrm.Yorum = y.Yorum;
            c.SaveChanges();
            return RedirectToAction("CommentList");
        }
    }
}

Views/admin/AddNewBlog.cshtml
@model TravelTrip_MVCProject.Models.Classes.BlogTBL

@{
    ViewBag.Title = "AddNewBlog";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2> Yeni Blog Ekle </h2>
<br />

<form method="post" class="form-group">
    <label class="form-label"> Başlık </label>
    @Html.TextBoxFor(b => b.Baslik, new { @class = "form-control", @required = "", @type = "text" })
    <br />
    <label class="form-label"> Blog Resmi </label>
    @Html.TextBoxFor(b => b.BlogFoto, new { @class = "form-control", required = "", @type = "text" })
    <br />
    <label class="form-label"> Tarih </label>
    @Html.TextBoxFor(b => b.Tarih, new { @class = "form-control", @required = "", @type = "date" })
    <br />
    <label class="form-label"> Blog İçeriği </label>
    @Html.TextAreaFor(b => b.Aciklama, 15, 1, new { @class = "form-control", @required = "", @type = "text" })
    <br />
    <div style="margin-bottom: 28px;">
        <a class="btn btn-outline-secondary" href="/admin/BlogList"> İptal </a>
        <button class="btn btn-success" type="submit"> Blog Kayıt Et </button>
    </div>
</form>

Views/admin/BlogList.cshtml
@using TravelTrip_MVCProject.Models.Classes
@model List<BlogTBL>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2> Bloglar </h2>
<br />

<a href="/admin/AddNewBlog/" class="btn btn-primary"> Yeni Blog Ekle </a>
<br /><br />

<table class="table table-bordered table-hover table-dark">
    <tr>
        <th> ID </th>
        <th> Başlık </th>
        <th> Tarih </th>
        <th> İşlemler </th>
    </tr>
    @foreach (var blog in Model)
    {
        <tr>
            <td> @blog.ID </td>
            <td> @blog.Baslik </td>
            <td> @blog.Tarih.ToShortDateString() </td>
            <td>
                <a href="/admin/DeleteBlog/@blog.ID" class="btn btn-danger process-btn"> Sil </a>
                <a href="/admin/UpdateBlog/@blog.ID" class="btn btn-info process-btn"> Güncelle </a>
                <a href="/blog/BlogDetail/@blog.ID" target="_blank" class="btn btn-outline-light"> Detaylar </a>
            </td>
        </tr>
    }
</table>

Views/admin/CommentList.cshtml
@using TravelTrip_MVCProject.Models.Classes
@model List<YorumlarTBL>

@{
    ViewBag.Title = "CommentList";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2> Yorumlar </h2>
<br />

<table class="table table-bordered table-hover table-dark">
    <tr>
        <th> ID </th>
        <th> İsim </th>
        <th> E-posta </th>
        <th> Yorum İçeriği </th>
        <th> Yazılan Blog </th>
        <th> İşlemler </th>
    </tr>

    @foreach (var y in Model)
    {
        <tr>
            <td>@y.ID</td>
            <td>@y.KullaniciAdi</td>
            <td>@y.Email</td>
            <td>@y.Yorum</td>
            <td>@y.Blog.Baslik</td>
            <td>
                <a href="/admin/DeleteComment/@y.ID" class="btn btn-danger process-btn"> Sil </a>
                <a href="/admin/UpdateComment/@y.ID" class="btn btn-info process-btn"> Güncelle </a>
            </td>
        </tr>
    }
</table>

Views/admin/UpdateBlog.cshtml
@model TravelTrip_MVCProject.Models.Classes.BlogTBL

@{
    ViewBag.Title = "UpdateBlog";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2> Blog Güncelle </h2>
<br />

@using (Html.BeginForm("UpdateBlog", "admin", FormMethod.Post))
{
    @Html.HiddenFor(b => b.ID)
    <label class="form-label"> Başlık </label>
    @Html.TextBoxFor(b => b.Baslik, new { @class = "form-control", @required = "", @type = "text" })
    <br />
    <label class="form-label"> Blog Resmi </label>
    @Html.TextBoxFor(b => b.BlogFoto, new { @class = "form-control", @required = "", @type = "text" })
    <br />
    <label class="form-label"> Tarih </label>
    @Html.TextBoxFor(b => b.Tarih, new { @class = "form-control", @required = "", @type = "text" })
    <br />
    <label class="form-label"> Blog İçeriği </label>
    @Html.TextAreaFor(b => b.Aciklama, 15, 1, new { @class = "form-control", @required = "", @type = "text" })
    <br />
    <div style="margin-bottom: 28px;">
        <a class="btn btn-outline-secondary" href="/admin/BlogList"> İptal </a>
        <button class="btn btn-success" type="submit"> Blog Güncelle </button>
    </div>
} 

Views/admin/UpdateComment.cshtml
@model TravelTrip_MVCProject.Models.Classes.YorumlarTBL

@{
    ViewBag.Title = "UpdateComment";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2> Yorum Güncelle </h2>
<br />

@using (Html.BeginForm("UpdateComment", "admin", FormMethod.Post))
{
    @Html.HiddenFor(y => y.ID)
    <label class="form-label"> İsim </label>
    @Html.TextBoxFor(y => y.KullaniciAdi, new { @class = "form-control", @required = "", @type="text" })
    <br />
    <label class="form-label"> E-posta </label>
    @Html.TextBoxFor(y => y.Email, new { @class = "form-control", @required = "", @type="email" })
    <br />
    <label class="form-label"> Yorum </label>
    @Html.TextAreaFor(y => y.Yorum, 5, 1, new { @class = "form-control", @required = "", @type="text" })
    <br />
    <div style="margin-bottom: 28px;">
        <a class="btn btn-outline-secondary" href="/admin/CommentList"> İptal </a>
        <button class="btn btn-success" type="submit"> Yorum Güncelle </button>
    </div>
}