Controllers/anasayfaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TravelTrip_MVCProject.Models.Classes;

namespace TravelTrip_MVCProject.Controllers
{
    public class anasayfaController : Controller
    {
        Context c = new Context();
        
        public ActionResult Index()
        {
            var blogs = c.BlogTBLs.Take(10).ToList();
            return View(blogs);
        }

        public PartialViewResult indexPartial1()
        {
            var values = c.BlogTBLs.OrderByDescending(x => x.ID).Take(4).ToList();
            return PartialView(values);
        }

        public PartialViewResult indexPartial2()
        {
            var values = c.BlogTBLs.Where(x => x.ID <= 8).OrderByDescending(x => x.ID).Take(4).ToList();
            return PartialView(values);
        }

        public PartialViewResult partialViewTop10()
        {
            var values = c.BlogTBLs.Take(10).ToList();
            return PartialView(values);
        }
    }
}

Views/anasayfa/Index.cshtml
@using TravelTrip_MVCProject.Models.Classes
@model List<BlogTBL>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_SiteLayout.cshtml";
}
<!--****** BURASI ANA SAYFA ******-->

<div class="header-banner">
    <div class="wrap">
        <div class="banner">
            <div class="indent">
                <h2 class="indent-left margin-bot"> Seyahat Günlüğümüz </h2>
                <div class="banner-left">
                    <div class="con-text">
                        <div class="grid1-img">
                            <img src="~/Themes/web/images/glass.png" alt="">
                        </div>
                        <div class="grid1-desc">
                            <p> Restaurantlar </p>
                        </div>
                        <div class="clear"></div>
                    </div>
                    <div class="con-text">
                        <div class="grid1-img">
                            <img src="~/Themes/web/images/flight.png" alt="">
                        </div>
                        <div class="grid1-desc">
                            <p> Uçuşlar </p>
                        </div>
                        <div class="clear"></div>
                    </div>
                    <div class="con-text">
                        <div class="grid1-img">
                            <img src="~/Themes/web/images/group.png" alt="">
                        </div>
                        <div class="grid1-desc">
                            <p> Yapılan Aktiviteler </p>
                        </div>
                        <div class="clear"></div>
                    </div>
                    <div class="con-text">
                        <div class="grid1-img">
                            <img src="~/Themes/web/images/key.png" alt="">
                        </div>
                        <div class="grid1-desc">
                            <p> Seyahat Püf Noktaları </p>
                        </div>
                        <div class="clear"></div>
                    </div>
                    <div class="clear"></div>
                </div>
                <div class="header_bottom_right_images">

                    <div class="slider" style="width: 640px; height: 360px;">
                        <ul class="rslides" id="slider1">
                            @foreach (var blogImage in Model)
                            {
                                <li><img src="@blogImage.BlogFoto" alt="Recent Blog Slider Images" style="height: 360px;"></li>
                            }
                        </ul>
                    </div>
                </div>
            </div>
            <div class="clear"></div>
        </div>
        <div class="clear"></div>
    </div>
</div>
<div class"content">
    <div class="wrap">
        <div class="wrapper">
            <div class="con-top">
                <h3> Biz Kimiz? </h3>
                <p> Bu proje ASP.Net MVC5'de CodeFirst Entity Framework yapısı kullanılarak Youtube'da bulunan 50 derslik bir eğitim serisi kapsamında örnek proje olarak geliştirilmiştir. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
                </p>
            </div><br />
            <div class="clear"></div>
            <div class="grids">
                <div class="box1">
                    @Html.Action("partialViewTop10", "anasayfa")

                    <!--** Anasayfa'da yer alan bölümü ilgili controllerdan Partial View oluşturarak aynı şekilde yapmış oldum. **-->
                    @Html.Action("indexPartial1", "anasayfa")
                    
                    <div class="clear"></div>
                </div>
            </div>
        </div>
    </div>
</div>

Views/anasayfa/indexPartial1.cshtml
@using TravelTrip_MVCProject.Models.Classes
@model List<BlogTBL>

    <!--** BURASI ANASAYFA CONTROLLERDA OLUŞTURDUĞUM 1. PARTIAL VIEW **-->

    <div class="padding1">
        <h4> Son Yayınlanan Yazılar </h4>
        <div class="box-left">
            @foreach (var blogList in Model)
            {
                <a href="/blog/BlogDetail/@blogList.ID" title="@blogList.Baslik" target="_blank">
                    <h5 style="margin-bottom: 6px;"> @blogList.Baslik </h5>
                    <div class="bot-img" style="width: 120px; height: 73px;">
                        <img src="@blogList.BlogFoto" alt="" />
                    </div>
                    <div class="bot-desc">
                        <p>@blogList.Aciklama.Substring(0, blogList.Aciklama.Substring(0, 80).LastIndexOf(" ")) ...</p>
                    </div>
                </a>
                <div class="clear"></div>
            }
        </div>

        @Html.Action("indexPartial2", "anasayfa")
    </div>

Views/anasayfa/indexPartial2.cshtml
@using TravelTrip_MVCProject.Models.Classes
@model List<BlogTBL>


<div class="box1-left">
    @foreach (var b in Model)
    {
        <a href="/blog/BlogDetail/@b.ID" title="@b.Baslik" target="_blank">
            <h5 style="margin-bottom: 6px;"> @b.Baslik </h5>
            <div class="bot-img">
                <img src="@b.BlogFoto" alt="" />
            </div>
            <div class="bot-desc">
                <p>@b.Aciklama.Substring(0, b.Aciklama.Substring(0, 80).LastIndexOf(" ")) ...</p>
            </div>
        </a>
        <div class="clear"></div>
    }
</div>

Views/anasayfa/partialViewTop10.cshtml
@using TravelTrip_MVCProject.Models.Classes
@model List<BlogTBL>

<div class="padding">
    <h4> En Çok Okunan 10 Yazı </h4>

    <ul class="list list-pad">
        @{ int i = 0; }
        @foreach (var blog10 in Model)
        {
            <li class="list-bg"><span>@{i++;} @i.</span><a href="/blog/BlogDetail/@blog10.ID"> @blog10.Baslik </a></li>
        }
    </ul>

</div>