Controllers/blogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TravelTrip_MVCProject.Models.Classes;

namespace TravelTrip_MVCProject.Controllers
{
    public class blogController : Controller
    {
        Context c = new Context();
        BlogYorum by = new BlogYorum();

        public ActionResult Index()
        {
            //var value = c.BlogTBLs.ToList();
            by.blogValue = c.BlogTBLs.ToList();
            by.recentBlog = c.BlogTBLs.OrderByDescending(x => x.Tarih).Take(3).ToList();
            return View(by);
        }

        public ActionResult BlogDetail(int id)
        {
            //* Statik olarak blogun ID'sine göre ilgili ayrıntı sayfasını açma.
            //var findBlog = c.BlogTBLs.Where(x => x.ID == id).ToList();
            
            //* BlogYorum sınıfından gelen interface değeri ile ID'ye göre ilgili blogları ve yorumları açma.
            by.blogValue = c.BlogTBLs.Where(x => x.ID == id).ToList();
            by.yorumValue = c.YorumlarTBLs.Where(x => x.Blogid == id).ToList();
            by.recentBlog = c.BlogTBLs.OrderByDescending(x => x.Tarih).Take(3).ToList();
            return View(by);
        }

        [HttpGet]
        public PartialViewResult partialCommentAdd(int id)
        {
            ViewBag.blogID = id;
            return PartialView();
        }

        [HttpPost]
        public PartialViewResult partialCommentAdd(YorumlarTBL y)
        {
            c.YorumlarTBLs.Add(y);
            c.SaveChanges();
            return PartialView(y);
        }
    }
}

Views/blog/BlogDetail.cshtml
@model TravelTrip_MVCProject.Models.Classes.BlogYorum

@{
    ViewBag.Title = "BlogDetail";
    Layout = "~/Views/Shared/_SiteLayout.cshtml";
}
<!--****** BURASI BLOG DETAY SAYFASI ******-->

<!DOCTYPE HTML>
<html>
<head>
    <link href="~/Themes/web-blog/css/bootstrap.css" rel='stylesheet' type='text/css' />
    <link href="~/Themes/web-blog/css/style.css" rel='stylesheet' type='text/css' />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <link href='http://fonts.googleapis.com/css?family=Oswald:100,400,300,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900,300italic' rel='stylesheet' type='text/css'>
</head>
<body>

    <div class="single">
        <div class="container">
            <div class="col-md-8 single-main">
                @foreach (var s in Model.blogValue)
                {
                    <div class="single-grid">
                        <img src="@s.BlogFoto" alt="Blog Image" />
                        <p style="margin-bottom:18px"> @s.Tarih.ToShortDateString() | Yazar: Admin | Kategorisiz </p>
                        <h1> @s.Baslik </h1>
                        <p style="margin-bottom:24px"> @s.Aciklama </p>
                    </div>
                }

                <div class="content-form">
                    <h3> Yazılan Yorumlar </h3>
                    <ul class="comment-list">
                        @foreach (var y in Model.yorumValue)
                        {
                            <li>
                                <div class="comments">
                                    <img src="~/Themes/web-blog/images/avatar.png" class="img-responsive" alt="comment avatar photo">
                                    <p><b>@y.KullaniciAdi dedi ki: </b><br />@y.Yorum</p>
                                </div>
                            </li>
                        }
                    </ul>
                </div>

                @Html.Action("partialCommentAdd", "blog")
            </div>

            <div class="col-md-4 side-content">
                <div class="recent">
                    <h3> Son 3 Blog </h3>
                    @foreach (var b in Model.recentBlog)
                    {
                        <ul>
                            <li><a href="/blog/BlogDetail/@b.ID"> @b.Baslik </a></li>
                        </ul>
                    }
                </div>
                <div class="comments">
                    <h3> Son 5 Yorum </h3>
                    <ul>
                        <li><a href="#">Amada Doe </a> on <a href="#">Hello World!</a></li>
                        <li><a href="#">Peter Doe </a> on <a href="#"> Photography</a></li>
                        <li><a href="#">Steve Roberts  </a> on <a href="#">HTML5/CSS3</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

</body>
</html>

Views/blog/Index.cshtml
@model TravelTrip_MVCProject.Models.Classes.BlogYorum

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_SiteLayout.cshtml";
}
<!--****** BURASI BLOG SAYFASI ******-->

<!DOCTYPE HTML>
<html>
<head>
    <link href="~/Themes/web-blog/css/bootstrap.css" rel='stylesheet' type='text/css' />
    <link href="~/Themes/web-blog/css/style.css" rel='stylesheet' type='text/css' />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <link href="http://fonts.googleapis.com/css?family=Oswald:100,400,300,700" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900,300italic" rel="stylesheet" type="text/css">
</head>
<body>

    <div class="single">
        <div class="container">
            <div class="col-md-8 single-main">
                @foreach (var s in Model.blogValue)
                {
                    <div class="single-grid">
                        <a href="/blog/BlogDetail/@s.ID" target="_blank"><img src="@s.BlogFoto" alt="" /></a>
                        <p style="margin-bottom:14px"> @s.Tarih.ToShortDateString() | Yazar: Admin | Kategorisiz </p>
                        <h1><a href="/blog/BlogDetail/@s.ID"> @s.Baslik </a></h1>
                        <p style="margin-bottom:28px"> @s.Aciklama.Substring(0, s.Aciklama.Substring(0, 350).LastIndexOf(" ")) ... Devamını okumak için tıkla. </p>
                    </div>
                }
            </div>
            <div class="col-md-4 side-content">
                <div class="recent">
                    <h3> Son 3 Yazı </h3>
                    @foreach (var y in Model.recentBlog)
                    {
                        <ul>
                            <li><a href="/blog/BlogDetail/@y.ID" target="_blank"> @y.Baslik </a></li>
                        </ul>
                    }
                </div>
                <div class="comments">
                    <h3> Son 5 Yorum </h3>
                    <ul>
                        <li><a href="#">Amada Doe </a> on <a href="#">Hello World!</a></li>
                        <li><a href="#">Peter Doe </a> on <a href="#"> Photography</a></li>
                        <li><a href="#">Steve Roberts  </a> on <a href="#">HTML5/CSS3</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

</body>
</html>

Views/blog/partialCommentAdd.cshtml
@model TravelTrip_MVCProject.Models.Classes.YorumlarTBL

<!--*** BURASI YORUM GÖNDERME PARTIAL VIEW SAYFASI ***-->

<div class="content-form">
    <h3> Bir Yorum Yaz </h3>
    <form method="post" class="form-group">
        <input name="Blogid" value="@ViewBag.blogID" hidden />
        <input type="text" class="form-control" placeholder="İsim" name="KullaniciAdi" style="margin-bottom: 10px" required />
        <input type="email" class="form-control" placeholder="E-postanız" name="Email" style="margin-bottom: 10px" required />
        <textarea placeholder="Yorumunuz" class="form-control" name="Yorum" required></textarea>
        <input value="Yorum Gönder" type="submit" />
    </form>
</div>